set character_set_client = 'utf8';

delete from banks;
delete from atmnetworks;

insert into atmnetworks (name, id) values ('Приватбанк','1');
insert into banks (name,webSite,network_id) values ('Приватбанк','https://privatbank.ua/','1');

insert into atmnetworks (name, id) values ('Атмосфера','2');
insert into banks (name,webSite,network_id) values ('ПАО «Креди Агриколь Банк»','http://credit-agricole.com.ua/rus/','2');
insert into banks (name,webSite,network_id) values ('ПАО «АКБ «Киев»','http://www.bank.kiev.ua','2');
insert into banks (name,webSite,network_id) values ('АКБ «Легбанк»','http://www.legbank.kiev.ua','2');
insert into banks (name,webSite,network_id) values ('АО «БМ Банк»','http://www.bmbank.com.ua','2');
insert into banks (name,webSite,network_id) values ('ПАО «БТА Банк»','http://www.bta.kiev.ua','2');
insert into banks (name,webSite,network_id) values ('ПАО «Диамантбанк»','http://www.diamantbank.ua/ru','2');
insert into banks (name,webSite,network_id) values ('ПАО «ВиЭйБи Банк»','http://www.vab.ua/rus/','2');
insert into banks (name,webSite,network_id) values ('ПАО «Альфа-Банк»','http://www.alfabank.ua','2');
insert into banks (name,webSite,network_id) values ('ПАО «Банк «Украинский капитал»','http://www.ukrcapital.com.ua','2');
insert into banks (name,webSite,network_id) values ('АО «ОТП Банк»','http://www.otpbank.com.ua/','2');
insert into banks (name,webSite,network_id) values ('ПАО «Дельта Банк»','http://www.deltabank.com.ua','2');
insert into banks (name,webSite,network_id) values ('АО «Сбербанк России»','http://sberbank.ua/','2');
insert into banks (name,webSite,network_id) values ('АБ «Пивденный»','http://www.bank.com.ua/','2');
insert into banks (name,webSite,network_id) values ('ПУАО «ФИДОБАНК»','http://www.fidobank.ua','2');
insert into banks (name,webSite,network_id) values ('ПАО «Банк Первый»','http://www.bankpershiy.com.ua/rus/','2');
insert into banks (name,webSite,network_id) values ('АО «Пиреус Банк МКБ»','http://www.piraeusbank.ua/ua/index.html','2');
insert into banks (name,webSite,network_id) values ('АО «Укринбанк»','http://www.ukrinbank.com/index.php?TemplateName=firstpage','2');
insert into banks (name,webSite,network_id) values ('ПАОКБ «ПРАВЭКС-БАНК»','http://www.pravex.com/rus','2');
insert into banks (name,webSite,network_id) values ('ПАО «Платинум Банк»','http://www.platinumbank.com.ua','2');
insert into banks (name,webSite,network_id) values ('ПАО «ВиЭс Банк»','http://www.vsbank.com.ua/ru/index','2');
insert into banks (name,webSite,network_id) values ('ПАО «Идея Банк»','http://www.ideabank.com.ua/','2');
insert into banks (name,webSite,network_id) values ('ПАО «АВАНТ-БАНК»','http://www.avantbank.com.ua','2');
insert into banks (name,webSite,network_id) values ('ПАО «Банк инвестиций и сбережений»','http://www.bisbank.com.ua/site/index.php?lang=RU','2');
insert into banks (name,webSite,network_id) values ('ПАО «КБ «АКТИВ-БАНК»','http://www.abank.com.ua/index.php?lang=ru','2');
insert into banks (name,webSite,network_id) values ('ПАО «Укргазпромбанк»','http://www.ugpb.com/index.php?cmd=page&pid=1','2');
insert into banks (name,webSite,network_id) values ('ПАО «Банк Михайловский»','http://www.mbank.kiev.ua/ru/index.htm','2');
insert into banks (name,webSite,network_id) values ('ПАО «Банк Камбио»','http://www.cambio.com.ua/site/ru/mainpage/','2');
insert into banks (name,webSite,network_id) values ('ПАО "Вернум банк"','http://vernumbank.com/','2');
insert into banks (name,webSite,network_id) values ('ПАО КБ «Финансовая Инициатива»','http://www.the-bank.com.ua/site/index.php?lang=RU','2');
insert into banks (name,webSite,network_id) values ('ПАО «Банк «Национальные инвестиции»','','2');

insert into atmnetworks (name, id) values ('Euronet','3');
insert into banks (name,webSite,network_id) values ('ПАТ "Банк Форвард"','http://forward-bank.com/','3');
insert into banks (name,webSite,network_id) values ('ПАТ "Банк Форум"','http://www.forum.ua/','3');
insert into banks (name,webSite,network_id) values ('ПАТ "УкрСиббанк"','http://www.ukrsibbank.com/','3');
insert into banks (name,webSite,network_id) values ('ПАТ "УніКредит Банк"','http://www.unicreditbank.com.ua/','3');

insert into atmnetworks (name, id) values ('Радіус','4');
insert into banks (name,webSite,network_id) values ('ПАТ КБ "Акордбанк"','http://www.accordbank.com.ua/','4');
insert into banks (name,webSite,network_id) values ('ПАТ "Актабанк"','http://www.aktabank.com/ua/','4');
insert into banks (name,webSite,network_id) values ('ПАТ "Банк 3/4"','http://www.bank34.ua/','4');
insert into banks (name,webSite,network_id) values ('ПАТ "Банк Камбіо"','http://www.cambio.com.ua/','4');
insert into banks (name,webSite,network_id) values ('ПАТ "Банк Кіпру"','http://www.bankofcyprus.com.ua/','4');
insert into banks (name,webSite,network_id) values ('ПАТ "Банк Кредит Дніпро"','http://creditdnepr.com.ua/ukr/','4');
insert into banks (name,webSite,network_id) values ('ПАТ "Банк Меркурій"','http://www.mercury-bank.com/','4');
insert into banks (name,webSite,network_id) values ('ПАТ "Банк Фамільний"','http://www.fbank.com.ua/','4');
insert into banks (name,webSite,network_id) values ('ПАТ "Всеукраїнський Банк Розвитку"','http://www.vbr-bank.com.ua/ua/','4');
insert into banks (name,webSite,network_id) values ('ПАТ Банк "Грант"','http://www.grant.kharkov.ua/','4');
insert into banks (name,webSite,network_id) values ('ПАТ "Європромбанк"','http://europrombank.com/','4');
insert into banks (name,webSite,network_id) values ('ПАТ АКБ «Індустріалбанк»','http://www.industrialbank.ua/','4');
insert into banks (name,webSite,network_id) values ('ПАТ АКБ "Капітал"','http://bank-capital.com/','4');
insert into banks (name,webSite,network_id) values ('ПАТ "Кредобанк"','http://www.kredobank.com.ua/','4');
insert into banks (name,webSite,network_id) values ('ПАТ АКБ "Львів"','http://www.banklviv.com/','4');
insert into banks (name,webSite,network_id) values ('ПАТ "Марфін Банк"','http://marfinbank.ua/UA/Pages/Home.aspx','4');
insert into banks (name,webSite,network_id) values ('ПАТ "МетаБанк"','http://www.mbank.com.ua/','4');
insert into banks (name,webSite,network_id) values ('ПАТ "Місто банк"','http://www.mistobank.com.ua/','4');
insert into banks (name,webSite,network_id) values ('ПАТ Банк "Морський"','http://www.bank.gov.ua/control/uk/publish/article?art_id=7361501','4');
insert into banks (name,webSite,network_id) values ('ПАТ "Мотор-банк"','http://motor-bank.ua/','4');
insert into banks (name,webSite,network_id) values ('ПАТ "Перший Інвестиційний Банк"','http://www.pinbank.ua/','4');
insert into banks (name,webSite,network_id) values ('ПАТ "Перший Український Міжнародний Банк"','http://pumb.ua/','4');
insert into banks (name,webSite,network_id) values ('ПАТ КБ "Південкомбанк"','http://www.pivdencombank.com/index.php?id=home_ukr','4');
insert into banks (name,webSite,network_id) values ('ПАТ "АБ "Порто-Франко"','http://www.porto-franco.com/','4');
insert into banks (name,webSite,network_id) values ('ПАТ "ПроКредит Банк"','http://www.procreditbank.com.ua/','4');
insert into banks (name,webSite,network_id) values ('ПАТ КБ "Промекономбанк"','http://www.peb.com.ua/','4');
insert into banks (name,webSite,network_id) values ('ПАТ "Промислово-фінансовий банк"','http://www.pfb.com.ua/','4');
insert into banks (name,webSite,network_id) values ('ПАТ "ПроФін Банк"','http://www.profinbank.com/','4');
insert into banks (name,webSite,network_id) values ('ПАТ "АБ "Радабанк"','http://www.radabank.com.ua/','4');
insert into banks (name,webSite,network_id) values ('ПАТ "Реал Банк"','http://realbank.com.ua/','4');
insert into banks (name,webSite,network_id) values ('ПАТ "Банк Ренесанс Капітал"','http://www.rccf.ua/','4');
insert into banks (name,webSite,network_id) values ('АТ "ТАСкомбанк"','http://www.tascombank.com.ua/index.php?lang=ukrainian','4');
insert into banks (name,webSite,network_id) values ('ПАТ АБ "Укоопспілка"','http://www.bankukoopspilka.kiev.ua/','4');
insert into banks (name,webSite,network_id) values ('ПАТ "Український Бізнес Банк"','http://ua.ubb.com.ua/','4');
insert into banks (name,webSite,network_id) values ('ПАТ "КБ "Український фінансовий світ"','http://www.fg.gov.ua/payments/ufs-83.html','4');
insert into banks (name,webSite,network_id) values ('ПАТ "Фінбанк"','http://www.finbank.odessa.ua/uk/','4');
insert into banks (name,webSite,network_id) values ('ПАТ "Фінростбанк"','http://www.frb.com.ua/ua/','4');

insert into atmnetworks (name, id) values ('УкрКард','5');
insert into banks (name,webSite,network_id) values ('ПАТ "Автокразбанк"','http://www.avtokrazbank.ua/','5');
insert into banks (name,webSite,network_id) values ('ПАТ "Банк Богуслав"','http://www.bankboguslav.com.ua/','5');
insert into banks (name,webSite,network_id) values ('ПАТ "Банк Велес"','http://www.bankveles.com/','5');
insert into banks (name,webSite,network_id) values ('ПАТ Банк "Контракт"','http://www.kontrakt.ua/','5');
insert into banks (name,webSite,network_id) values ('ПАТ "Банк Народний Капітал"','http://www.nkbank.com.ua/','5');
insert into banks (name,webSite,network_id) values ('ПАТ "Банк Національний Кредит"','http://bnk.ua/ua/golovna','5');
insert into banks (name,webSite,network_id) values ('ПАТ "КБ "Даніель"','http://www.danielbank.kiev.ua/','5');
insert into banks (name,webSite,network_id) values ('АТ "ЄВРОГАЗБАНК"','http://www.egb.kiev.ua/uk.html','5');
insert into banks (name,webSite,network_id) values ('ПАТ "Західінкомбанк"','http://www.inkom.lutsk.ua/','5');
insert into banks (name,webSite,network_id) values ('ПАТ "Інтеграл-банк"','http://www.integral.com.ua/uk','5');
insert into banks (name,webSite,network_id) values ('ПАТ Банк "Київська Русь"','http://www.kruss.kiev.ua/','5');
insert into banks (name,webSite,network_id) values ('ПАТ "Комерційний Індустріальний Банк"','http://cib.com.ua/','5');
insert into banks (name,webSite,network_id) values ('ПАТ "КомІнвестБанк"','http://www.atcominvestbank.com/','5');
insert into banks (name,webSite,network_id) values ('ПАТ "Міський комерційний банк"','http://ua.citycommercebank.com/','5');
insert into banks (name,webSite,network_id) values ('ПАТ "Оксі Банк"','http://www.okcibank.com.ua/','5');
insert into banks (name,webSite,network_id) values ('ПАТ "Полтава-банк"','http://www.poltavabank.com/','5');
insert into banks (name,webSite,network_id) values ('ПАТ "Радикал Банк"','http://radicalbank.ua/','5');
insert into banks (name,webSite,network_id) values ('ПАТ "АКБ "Траст-капітал"','http://www.tc-bank.com/','5');
insert into banks (name,webSite,network_id) values ('ПАТ "Український професійний банк"','http://upb.ua/','5');
insert into banks (name,webSite,network_id) values ('ПАТ "Укргазбанк"','http://www.ukrgasbank.com.ua/','5');
insert into banks (name,webSite,network_id) values ('ПАТ "КБ "Фінансова ініціатива"','http://www.finbank.com.ua/','5');
insert into banks (name,webSite,network_id) values ('ПАТ "Юнекс Банк"','http://www.unexbank.ua/','5');
