package com.ss.atmlocator.dao;

import com.ss.atmlocator.entity.AtmNetwork;
import com.ss.atmlocator.entity.Bank;
import com.ss.atmlocator.utils.TimeUtil;
import org.apache.log4j.Logger;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

import javax.persistence.EntityManager;
import javax.persistence.NoResultException;
import javax.persistence.PersistenceContext;
import javax.persistence.TypedQuery;;
import java.sql.Timestamp;
import java.util.List;

/**
 * Created by Olavin on 22.11.2014.
 */
@Repository
public class BanksDAO implements IBanksDAO {
    private static final int UNASSIGNED_NETWORK = -1;
    private final org.apache.log4j.Logger log = Logger.getLogger(BanksDAO.class);

    @PersistenceContext
    private EntityManager entityManager;

    @Override
    public List<Bank> getBanksList() {
        List<Bank> banks;
        TypedQuery<Bank> query = entityManager.createQuery("SELECT b FROM Bank AS b ORDER BY b.name",Bank.class);
        banks = query.getResultList();
        return banks;
    }

    @Override
    @Transactional
    public Bank newBank() {
        Bank bank = new Bank();
        bank.setId(0); // ID for new Bank autogenerated by database
        AtmNetwork network = entityManager.find(AtmNetwork.class, UNASSIGNED_NETWORK);
        bank.setNetwork(network);
        bank.setLogo("default_logo.png");
        bank.setIconAtm("default_atm.png");
        bank.setIconOffice("default_office.png");
        bank.setLastUpdated(TimeUtil.currentTimestamp());
        return bank;
    }

    @Override
    public Bank getBank(int id) {
        Bank bank = (Bank) entityManager.find(Bank.class, id);
        return bank;
    }

    @Override
    public List<Bank> getBanksByNetworkId(int network_id) {
        TypedQuery<Bank> query = entityManager.createQuery("SELECT b FROM Bank AS b " +
                "where b.network.id=:network_id ORDER BY b.name",Bank.class);
        query.setParameter("network_id", network_id);
        return query.getResultList();
    }

    @Override
    @Transactional
    public Bank saveBank(Bank bank) {
        bank.setLastUpdated(TimeUtil.currentTimestamp());
        Bank saved = (Bank) entityManager.merge(bank);
        log.debug("Saved Bank '"+saved.getName()+"' #"+saved.getId());
        return saved;
    }

    @Override
    @Transactional
    public void deleteBank(int bank_id) {
        Bank bank = (Bank) entityManager.find(Bank.class, bank_id);
        String delName = bank.getName(); //get name before it will be deleted
        entityManager.remove(bank);
        log.debug("Deleted Bank '"+delName+"' #"+bank_id);
    }

    /*'*/
//    @Override
//    @Transactional
//    public void saveAllBankNBU(List<Bank> banks) {
//        for(Bank bank: banks){
//            entityManager.merge(bank);
//        }
//    }
    @Override
    @Transactional
    public void saveAllBankNBU(List<Bank> banks) {
        Bank bank1;
        AtmNetwork unassigned = entityManager.find(AtmNetwork.class, UNASSIGNED_NETWORK);

        for (Bank bank : banks) {
            int mfoCode = bank.getMfoCode();
            try {
                TypedQuery<Bank> query = entityManager.createQuery("SELECT b FROM Bank AS b WHERE b.mfoCode=:mfoCode", Bank.class);
                query.setParameter("mfoCode", mfoCode);

                bank1 = query.getSingleResult();// тут вилітає , бо query не повертає щось не те

                if (bank.getMfoCode() == bank1.getMfoCode()) {
                    System.out.println("------I'm in continue-----");
                    continue;
                }
            } catch (NoResultException nre) {
                //if the bank with mfo code not found , catch this exception
//                continue;
            }
            bank.setLastUpdated(TimeUtil.currentTimestamp());
            bank.setNetwork(unassigned);
            entityManager.merge(bank);
        }
    }


}
